- name: Basic Setup
  hosts: local
  become: yes

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Start Apache
      service:
        name: apache2
        state: started

    - name: Enable Apache
      service:
        name: apache2
        enabled: yes
